#!/bin/sh
############################
#System Master Skript      #
#TeTesept		   #
############################

modprobe ip_conntrack
modprobe ip_conntrack_ftp

# variables

tcp_in="22"
udp_in=""
tcp_out="20,21,22,25,53,80,443"
udp_out="53,123,514"

# set every CHAIN to DROP
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP

# Create specific rules
iptables -N FTP
iptables -N SSH

# Flush (-F) all specific rules
iptables -F INPUT
iptables -F FORWARD
iptables -F OUTPUT
iptables -F FTP
iptables -F SSH
ip6tables -F INPUT
ip6tables -F FORWARD
ip6tables -F OUTPUT
ip6tables -F FTP
ip6tables -F SSH

# Permit packets in to firewall itself that are part of existing and related connections.
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow all inputs to firewall from the loopback interface
iptables -A INPUT -i lo -j ACCEPT
ip6tables -A INPUT -i lo -j ACCEPT

# Allow all output to firewall from the loopback interface
iptables -A OUTPUT -o lo -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT

# Brute-Force Limit
iptables -A FTP -p tcp --syn --dport 21 -m recent --name ftpattack --set
iptables -A FTP -p tcp --dport 21 --syn -m recent --name ftpattack --rcheck --seconds 1800 --hitcount 15 -j LOG --log-prefix 'BF-FTP: ' -m limit --limit 1/hour --limit-burst 1
iptables -A FTP -p tcp --dport 21 --syn -m recent --name ftpattack --rcheck --seconds 1800 --hitcount 15 -j REJECT --reject-with tcp-reset

iptables -A SSH -p tcp --syn --dport 22 -m recent --name sshattack --set
iptables -A SSH -p tcp --dport 22 --syn -m recent --name sshattack --rcheck --seconds 1800 --hitcount 15 -j LOG --log-prefix 'BF-SSH: ' -m limit --limit 1/hour --limit-burst 1
iptables -A SSH -p tcp --dport 22 --syn -m recent --name sshattack --rcheck --seconds 1800 --hitcount 15 -j REJECT --reject-with tcp-reset

# INCOMING ICMP
iptables -A INPUT -p icmp -j ACCEPT
ip6tables -A INPUT -p icmpv6 -j ACCEPT

# OUTGOING ICMP
iptables -A OUTPUT -p icmp -j ACCEPT
ip6tables -A OUTPUT -p icmpv6 -j ACCEPT

#Loging
#iptables -A INPUT -m tcp -p tcp -j LOG --log-level info --log-prefix "Iptables TCP denied "
#iptables -A INPUT -m udp -p udp -j LOG --log-level info --log-prefix "Iptables UDP denied "
#iptables -A OUTPUT -m tcp -p tcp -j LOG --log-level info --log-prefix "Iptables TCP denied "
#iptables -A OUTPUT -m udp -p udp -j LOG --log-level info --log-prefix "Iptables UDP denied "

# INCOMING SYN packets for protocol TCP
iptables -A INPUT -p tcp --sport 1024: -m multiport --destination-ports $tcp_in --syn -j ACCEPT

# OUTGOING SYN packets for protocol TCP
iptables -A OUTPUT -p tcp -m multiport --destination-ports $tcp_out --syn -j ACCEPT

# INCOMING packets for protocol UDP
#iptables -A INPUT -p udp --sport 1024: -m multiport --destination-ports $udp_in -j ACCEPT

# OUTGOING packets for protocol UDP
iptables -A OUTPUT -p udp -m multiport --destination-ports $udp_out -j ACCEPT

#-----------------------------------------USER-RULES-------------------------------------------------------




